name: Generate Snake

on:
  schedule: # roda automaticamente uma vez por dia
    - cron: "0 0 * * *"  # meia-noite UTC
  workflow_dispatch: # roda manualmente também

jobs:
  build:
    name: Generate GitHub Contribution Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: gabrielhsartori
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push the snake animation to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
